swagger: "2.0"
info:
  version: "1.0.0"
  title: "CheckMyMole API"
host: "prod.api.checkmoleapp.demo-redisys.com"
tags:
- name: "User"
- name: "Body parts"
- name: "Questions"
- name: "Lesions"
- name: "Requests"
schemes:
- "https"
paths:
  /users/me:
    get:
      tags:
      - "User"
      summary: "Get the details of the current user"
  /body-parts:
    get:
      tags:
      - "Body parts"
      summary: "List all body parts ordered by \"order\""
    post:
      tags:
      - "Body parts"
      summary: "Create a new body part"
      security:
      - checkmoleapp_auth:
        - "body-parts.write"
  /body-parts/{id}:
    put:
      tags:
      - "Body parts"
      summary: "Update an existing body part"
      security:
      - checkmoleapp_auth:
        - "body-parts.write"
    delete:
      tags:
      - "Body parts"
      summary: "Delete an existing body part"
      security:
      - checkmoleapp_auth:
        - "body-parts.write"
  /questions:
    get:
      tags:
      - "Questions"
      summary: "List all questions ordered by \"order\""
    post:
      tags:
      - "Questions"
      summary: "Create a new question"
      security:
      - checkmoleapp_auth:
        - "questions.write"
  /questions/{id}:
    put:
      tags:
      - "Questions"
      summary: "Update an existing question"
      security:
      - checkmoleapp_auth:
        - "questions.write"
    delete:
      tags:
      - "Questions"
      summary: "Delete an existing question"
      security:
      - checkmoleapp_auth:
        - "questions.write"
  /users/me/lesions:
    get:
      tags:
      - "Lesions"
      summary: "List all of user's lesions"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    post:
      tags:
      - "Lesions"
      summary: "Create a new lesion"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /users/me/lesions/{id}:
    put:
      tags:
      - "Lesions"
      summary: "Update an existing lesion"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    delete:
      tags:
      - "Lesions"
      summary: "Delete an existing lesion"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /users/me/requests:
    get:
      tags:
      - "Requests"
      summary: "List all of user's requests"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    post:
      tags:
      - "Requests"
      summary: "Create a new request"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /users/me/requests/{id}:
    get:
      tags:
      - "Requests"
      summary: "Gets a single request with related objects"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.read"
    put:
      tags:
      - "Requests"
      summary: "Update an existing request"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    delete:
      tags:
      - "Requests"
      summary: "Delete an existing request"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /users/me/lesions/{lesion}/reports:
    get:
      tags:
      - "Reports"
      summary: "List all of the reports in the lesion"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    post:
      tags:
      - "Reports"
      summary: "Create a new report"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /users/me/lesions/{lesion}/reports/{id}:
    put:
      tags:
      - "Reports"
      summary: "Update an existing report"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
    delete:
      tags:
      - "Reports"
      summary: "Delete an existing report"
      security:
      - checkmoleapp_auth:
        - "owned.lesions.write"
  /requests:
    get:
      tags:
      - "Requests"
      summary: "List all of the requests in the system"
      security:
      - checkmoleapp_auth:
        - "requests.read"
  /requests/{id}:
    get:
      tags:
      - "Requests"
      summary: "Get a single request by its ID"
      security:
      - checkmoleapp_auth:
        - "requests.read"
    put:
      tags:
      - "Requests"
      summary: "Allows doctors to update a request (including changing answer and state to answered)"
      security:
      - checkmoleapp_auth:
        - "requests.respond"
  /lesions:
    get:
      tags:
      - "Lesions"
      summary: "List all of the lesions in the system"
      security:
      - checkmoleapp_auth:
        - "lesions.read"
  /lesions/{id}:
    get:
      tags:
      - "Lesions"
      summary: "Get a single lesion by its ID"
      security:
      - checkmoleapp_auth:
        - "lesions.read"
  /reports:
    get:
      tags:
      - "Reports"
      summary: "List all of the reports in the system"
      security:
      - checkmoleapp_auth:
        - "reports.read"
  /reports/{id}:
    get:
      tags:
      - "Reports"
      summary: "Get a single report by its ID"
      security:
      - checkmoleapp_auth:
        - "reports.read"

securityDefinitions:
  checkmoleapp_auth:
    type: "oauth2"
    authorizationUrl: "https://auth.checkmoleapp.demo-redisys.com/login"
    flow: "implicit"
    scopes:
      body-parts.write: "create, update and delete body parts"
      questions.write: "create, update and delete questions"
      owned.lesions.read: "read lesions, reports and requests owned by the user"
      owned.lesions.write: "modify lesions, reports and requests owned by the user"
      requests.read: "read all requests in the system"
      reports.read: "read all reports in the system"
      requests.respond: "update all requests in the system"
      lesions.read: "read all lesions in the system"